apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
    app: wordpress
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
        app: wordpress
    spec:
      containers:
        - name: slave
          image: bitnami/mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_REPLICATION_MODE
              value: slave
            - name: MYSQL_REPLICATION_USER
              value: wpcluster
            - name: MYSQL_REPLICATION_PASSWORD
              value: 1qazXSW2
            - name: MYSQL_MASTER_HOST
              value: mysql-master
            - name: MYSQL_MASTER_ROOT_PASSWORD
              value: 1qazXSW2
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
    app: wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: mysql-slave
