apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wordpress-pv
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
    app: wordpress
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
        app: wordpress
    spec:
      containers:
        - name: master
          image: bitnami/mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: P@ssw0rd
            - name: MYSQL_REPLICATION_MODE
              value: master
            - name: MYSQL_REPLICATION_USER
              value: wpcluster
            - name: MYSQL_REPLICATION_PASSWORD
              value: P@ssw0rd
            - name: MYSQL_USER
              value: wpuser
            - name: MYSQL_PASSWORD
              value: P@ssw0rd
            - name: MYSQL_DATABASE
              value: wordpress
          volumeMounts:
          - name: mysql-wordpress-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-wordpress-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-wordpress-master
  labels:
    name: mysql-master
    app: wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: mysql-master

